import MLSFormal.Chemistry
import MLSFormal.CoarseGraining
import MLSFormal.Conservation
import MLSFormal.Scaling
import MLSFormal.SimulationSafety
import MLSFormal.TransitionModel
import MLSFormal.TransferLab
import MLSFormal.AffineAdvection
import MLSFormal.MovingAPICLimit
import MLSFormal.ConsistentProjection
import MLSFormal.ProjectionNullspace
import MLSFormal.MechanicalObservability
import MLSFormal.KelvinCovariance
import MLSFormal.RelationalObservability
import MLSFormal.ConstitutiveExpressivity

/-!
Complete kernel axiom report for every theorem exported by the MLSFormal
modules. Keep this list synchronized with project theorem declarations; CI also
scans project sources for proof placeholders and project-defined axioms.
-/

#print axioms MLSFormal.pairTransfer_preserves_total
#print axioms MLSFormal.pairTransfer_preserves_nonnegativity
#print axioms MLSFormal.equalOppositeImpulse_preserves_momentum
#print axioms MLSFormal.chemicalThermalConversion_preserves_energy
#print axioms MLSFormal.worldReservoirExchange_preserves_energy
#print axioms MLSFormal.disjointAggregation_preserves_total
#print axioms MLSFormal.balancedReaction_preserves_elements
#print axioms MLSFormal.aggregation_preserves_reactantTotals
#print axioms MLSFormal.conservativeAggregation_canInventReaction
#print axioms MLSFormal.reynolds_scale_invariant
#print axioms MLSFormal.froudeSquared_scale_invariant
#print axioms MLSFormal.peclet_scale_invariant
#print axioms MLSFormal.damkohlerFirstOrder_scale_invariant
#print axioms MLSFormal.identityCompression_isSafe
#print axioms MLSFormal.interventionalAgreement_oneStep
#print axioms MLSFormal.transferHeat_preserves_energy
#print axioms MLSFormal.applyReaction_preserves_element
#print axioms MLSFormal.replaceStructuralEnergy_preserves_energy
#print axioms MLSFormal.boundaryMaterialTransfer_preserves_material
#print axioms MLSFormal.boundaryEnergyTransfer_preserves_energy
#print axioms MLSFormal.actuatedDissipativePairImpulse_preserves_momentum
#print axioms MLSFormal.actuatedDissipativePairImpulse_preserves_energy
#print axioms MLSFormal.pairImpulse_orbitalAngular_delta
#print axioms MLSFormal.centralActuatedDissipativePairImpulse_preserves_angularMomentum
#print axioms MLSFormal.boundaryPointImpulse_preserves_momentum
#print axioms MLSFormal.boundaryPointImpulse_preserves_angularMomentum
#print axioms MLSFormal.boundaryPointImpulse_preserves_energy
#print axioms MLSFormal.p2gMass_preserves_mass
#print axioms MLSFormal.p2gPIC_preserves_linearMomentum
#print axioms MLSFormal.p2gAPIC_preserves_linearMomentum
#print axioms MLSFormal.g2pPIC_reproduces_constant
#print axioms MLSFormal.g2pPIC_reproduces_affineVelocity
#print axioms MLSFormal.g2pAPIC_reproduces_affine
#print axioms MLSFormal.p2gAPIC_preserves_angularMomentum
#print axioms MLSFormal.convectedAffine_preserves_material_velocity
#print axioms MLSFormal.staleAffineGradient_exact_defect
#print axioms MLSFormal.convectedAffine_two_half_steps_material_refinement
#print axioms MLSFormal.convectedGenerator_preserves_material_velocity
#print axioms MLSFormal.convectedGenerator_two_half_steps_equal_full_step
#print axioms MLSFormal.homogeneousAffineGenerator_on_position
#print axioms MLSFormal.homogeneousGeneratorStep_on_position
#print axioms MLSFormal.homogeneousAffineStepInverse_is_inverse
#print axioms MLSFormal.convectedHomogeneousAffineGenerator_formula
#print axioms MLSFormal.convectedAffine_two_half_steps_equal_full_update
#print axioms MLSFormal.movingAPIC_nextParticleVelocity_affine
#print axioms MLSFormal.movingAPIC_nextParticlePosition_affine
#print axioms MLSFormal.movingAPIC_newOffset_affine
#print axioms MLSFormal.movingAPIC_eq38_affine_BNext
#print axioms MLSFormal.movingAPIC_eq38_affine_BNext_expanded
#print axioms MLSFormal.movingAPIC_CNext_eq_oldGradient_when_moment_fixed
#print axioms MLSFormal.movingAPIC_staleGradient_exact_discrepancy
#print axioms MLSFormal.movingAPIC_CNext_minus_exactAffineGradient
#print axioms MLSFormal.consistentMass_is_gram_operator
#print axioms MLSFormal.consistentMass_kernel_eq_interpolation_kernel
#print axioms MLSFormal.consistentProjection_solutions_have_equal_reconstruction
#print axioms MLSFormal.consistentProjection_affine_rhs_relation
#print axioms MLSFormal.consistentProjection_unique_grid_recovery
#print axioms MLSFormal.consistentProjection_affine_particle_recovery
#print axioms MLSFormal.consistentProjection_preserves_linear_momentum
#print axioms MLSFormal.consistentProjection_preserves_orbital_angular_momentum
#print axioms MLSFormal.centralRigidityMatrix_mulVec
#print axioms MLSFormal.centralRigidity_exact_squared_length_expansion
#print axioms MLSFormal.centralRigidity_translation_in_kernel
#print axioms MLSFormal.centralRigidity_infinitesimal_rotation_in_kernel
#print axioms MLSFormal.rigidMotionSubspace_le_centralRigidity_kernel
#print axioms MLSFormal.mechanicallyObservable_iff_every_kernel_motion_rigid
#print axioms MLSFormal.rationalTetraK4_mechanicallyObservable
#print axioms MLSFormal.rationalTetra_rigidMotionGenerator_injective
#print axioms MLSFormal.rationalTetra_rigidMotionSubspace_finrank
#print axioms MLSFormal.rationalTetraK4_kernel_finrank
#print axioms MLSFormal.rationalTetraK4_range_finrank
#print axioms MLSFormal.rationalTetraMissingRelation_floppy_in_kernel
#print axioms MLSFormal.rationalTetraMissingRelation_floppy_not_rigid
#print axioms MLSFormal.rationalTetraMissingRelation_not_mechanicallyObservable
#print axioms MLSFormal.transformedRawCorrectedSymmetricGradient_translation_independent
#print axioms MLSFormal.transformedRawCorrectedSymmetricGradient_mul_inputRotation
#print axioms MLSFormal.transformedRawCorrectedSymmetricGradient_descaled_gram
#print axioms MLSFormal.transformedRawCorrectedSymmetricGradient_raw_spectrum_covariant
#print axioms MLSFormal.diagnosticKelvinBlockScale_covariant
#print axioms MLSFormal.kelvinRowMixing_orthogonal
#print axioms MLSFormal.kelvinRowNormalizationCounterexample_raw_gram_covariant
#print axioms MLSFormal.kelvinRowNormalizationCounterexample_exact_normalizations
#print axioms MLSFormal.kelvinRowsNormalizedBeforeMixing_unit_rows
#print axioms MLSFormal.kelvinRowsNormalizedAfterMixing_unit_rows
#print axioms MLSFormal.scalarRowNormalization_destroys_raw_spectrum_covariance
#print axioms MLSFormal.relabelVertexField_apply_rename
#print axioms MLSFormal.relationOffset_vertex_relabel
#print axioms MLSFormal.relationMotion_vertex_relabel
#print axioms MLSFormal.relationSquaredLength_vertex_relabel
#print axioms MLSFormal.centralRigidityRate_vertex_relabel
#print axioms MLSFormal.centralRigidityOperator_vertex_relabel
#print axioms MLSFormal.centralRigidityMatrix_vertex_relabel
#print axioms MLSFormal.centralRigidity_kernel_vertex_relabel_iff
#print axioms MLSFormal.relabelVertexField_mem_rigidMotionSubspace_iff
#print axioms MLSFormal.mechanicallyObservable_vertex_relabel_iff
#print axioms MLSFormal.centralOrthogonal3_preserves_dot3
#print axioms MLSFormal.relationOffset_similarity
#print axioms MLSFormal.relationMotion_rotation
#print axioms MLSFormal.relationSquaredLength_similarity
#print axioms MLSFormal.centralRigidityRate_similarity
#print axioms MLSFormal.centralRigidityOperator_similarity
#print axioms MLSFormal.centralRigidity_kernel_similarity_iff
#print axioms MLSFormal.relationSquaredLength_rigid_objective
#print axioms MLSFormal.centralRigidityOperator_rigid_objective
#print axioms MLSFormal.relabeledRationalTetraK4_mechanicallyObservable
#print axioms MLSFormal.relabeledRationalTetraMissingRelation_not_mechanicallyObservable
#print axioms MLSFormal.relationalStiffness_quadratic_identity
#print axioms MLSFormal.relationalQuadraticEnergy_eq_stiffness_quadratic
#print axioms MLSFormal.relationalStiffness_symmetric
#print axioms MLSFormal.relationKernel_le_relationalStiffnessKernel
#print axioms MLSFormal.relationalStiffness_kernel_eq_relationKernel
#print axioms MLSFormal.rigidRelationMotion_in_relationalStiffnessKernel
#print axioms MLSFormal.observableRelationalStiffness_has_only_rigid_kernel
#print axioms MLSFormal.relationalQuadraticEnergy_objective_of_extension_eq
#print axioms MLSFormal.relationalQuadraticEnergy_extension_scale
