import MLSFormal.Chemistry
import MLSFormal.CoarseGraining
import MLSFormal.Conservation
import MLSFormal.Scaling
import MLSFormal.SimulationSafety
import MLSFormal.TransitionModel
import MLSFormal.TransferLab
import MLSFormal.AffineAdvection
import MLSFormal.MovingAPICLimit

/-!
Complete kernel axiom report for every theorem exported by the MLSFormal
modules. Keep this list synchronized with project theorem declarations; CI also
scans project sources for proof placeholders and project-defined axioms.
-/

#print axioms MLSFormal.pairTransfer_preserves_total
#print axioms MLSFormal.pairTransfer_preserves_nonnegativity
#print axioms MLSFormal.equalOppositeImpulse_preserves_momentum
#print axioms MLSFormal.chemicalThermalConversion_preserves_energy
#print axioms MLSFormal.worldReservoirExchange_preserves_energy
#print axioms MLSFormal.disjointAggregation_preserves_total
#print axioms MLSFormal.balancedReaction_preserves_elements
#print axioms MLSFormal.aggregation_preserves_reactantTotals
#print axioms MLSFormal.conservativeAggregation_canInventReaction
#print axioms MLSFormal.reynolds_scale_invariant
#print axioms MLSFormal.froudeSquared_scale_invariant
#print axioms MLSFormal.peclet_scale_invariant
#print axioms MLSFormal.damkohlerFirstOrder_scale_invariant
#print axioms MLSFormal.identityCompression_isSafe
#print axioms MLSFormal.interventionalAgreement_oneStep
#print axioms MLSFormal.transferHeat_preserves_energy
#print axioms MLSFormal.applyReaction_preserves_element
#print axioms MLSFormal.replaceStructuralEnergy_preserves_energy
#print axioms MLSFormal.boundaryMaterialTransfer_preserves_material
#print axioms MLSFormal.boundaryEnergyTransfer_preserves_energy
#print axioms MLSFormal.actuatedDissipativePairImpulse_preserves_momentum
#print axioms MLSFormal.actuatedDissipativePairImpulse_preserves_energy
#print axioms MLSFormal.pairImpulse_orbitalAngular_delta
#print axioms MLSFormal.centralActuatedDissipativePairImpulse_preserves_angularMomentum
#print axioms MLSFormal.boundaryPointImpulse_preserves_momentum
#print axioms MLSFormal.boundaryPointImpulse_preserves_angularMomentum
#print axioms MLSFormal.boundaryPointImpulse_preserves_energy
#print axioms MLSFormal.p2gMass_preserves_mass
#print axioms MLSFormal.p2gPIC_preserves_linearMomentum
#print axioms MLSFormal.p2gAPIC_preserves_linearMomentum
#print axioms MLSFormal.g2pPIC_reproduces_constant
#print axioms MLSFormal.g2pPIC_reproduces_affineVelocity
#print axioms MLSFormal.g2pAPIC_reproduces_affine
#print axioms MLSFormal.p2gAPIC_preserves_angularMomentum
#print axioms MLSFormal.convectedAffine_preserves_material_velocity
#print axioms MLSFormal.staleAffineGradient_exact_defect
#print axioms MLSFormal.convectedAffine_two_half_steps_material_refinement
#print axioms MLSFormal.convectedGenerator_preserves_material_velocity
#print axioms MLSFormal.convectedGenerator_two_half_steps_equal_full_step
#print axioms MLSFormal.homogeneousAffineGenerator_on_position
#print axioms MLSFormal.homogeneousGeneratorStep_on_position
#print axioms MLSFormal.homogeneousAffineStepInverse_is_inverse
#print axioms MLSFormal.convectedHomogeneousAffineGenerator_formula
#print axioms MLSFormal.convectedAffine_two_half_steps_equal_full_update
#print axioms MLSFormal.movingAPIC_nextParticleVelocity_affine
#print axioms MLSFormal.movingAPIC_nextParticlePosition_affine
#print axioms MLSFormal.movingAPIC_newOffset_affine
#print axioms MLSFormal.movingAPIC_eq38_affine_BNext
#print axioms MLSFormal.movingAPIC_eq38_affine_BNext_expanded
#print axioms MLSFormal.movingAPIC_CNext_eq_oldGradient_when_moment_fixed
#print axioms MLSFormal.movingAPIC_staleGradient_exact_discrepancy
#print axioms MLSFormal.movingAPIC_CNext_minus_exactAffineGradient
